export class OrderTable{
    title:string;

    table:{
        id:string;
        name:string;
        subName:string;
        subNameAfter:string;
        linkTipLabel:string;
    }[];
    dropList:{
        listNodes:Array<{
            id:string;
            name:string; 
         }>;
         fontSize:string;
         defaultId:string;
         eventType:number;
    }
    dropListV1:{
        listNodes:Array<{
            id:string;
            name:string; 
         }>;
         fontSize:string;
         defaultId:string;
         eventType:number;
    }
}